service: product-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  profile: Aliaksandr_Baryskin
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    TABLE_NAME_PRODUCTS: 'AWS_Products'
    TABLE_NAME_PRODUCTS_STOCK: 'AWS_Products_Stock'

plugins:
  - serverless-webpack

functions:
  getProductsList:
    handler: handlers/getProductsList.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsById:
    handler: handlers/getProductsById.getProductsById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
  createProduct:
    handler: handlers/createProduct.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true
