service: product-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  profile: Aliaksandr_Baryskin
  environment:
    TABLE_NAME_PRODUCTS: 'AWS_Products'
    TABLE_NAME_PRODUCTS_STOCK: 'AWS_Products_Stock'
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 
        - sns:Publish
      Resource: 
        - 'arn:aws:sns:us-east-1:222048563468:createProductTopic'

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

resources:
  Resources:
    AdditionalSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: 'sanya.boriskim@gmail.com'
        Protocol: email
        TopicArn: arn:aws:sns:us-east-1:222048563468:createProductTopic
        FilterPolicyScope: 'MessageBody'
        FilterPolicy: { price: [{ "numeric": [">", 3] }] }

functions:
  getProductsList:
    handler: handlers/getProductsList.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsById:
    handler: handlers/getProductsById.getProductsById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
  createProduct:
    handler: handlers/createProduct.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true
  catalogBatchProcess:
    handler: handlers/catalogBatchProcess.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn: arn:aws:sqs:us-east-1:222048563468:catalogItemsQueue
