service: authorization-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  profile: Aliaksandr_Baryskin
  environment:
    AliaksandrBaryskin: 'TEST_PASSWORD'

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  basicAuthorizer:
    handler: handlers/basicAuthorizer.basicAuthorizer
